---
networks:
  traefik_proxy:
    external: true

services:
  app:
    build: "./"
    image: "localbuild/siemens_exporter"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "siemens_exporter"
    networks:
      - traefik_proxy
{% if dapp_siemens_exporter_docker_mem_limit is defined %}
    mem_limit: {{ dapp_siemens_exporter_docker_mem_limit }}
{% endif %}
    ports:
      {{ dapp_siemens_exporter_docker_ports|to_nice_yaml|indent(6) }}
    environment:
      {{ dapp_siemens_exporter_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_siemens_exporter_docker_healthcheck|indent(6) }}
    labels:
      traefik.enable: "false"
