---
- name: Set project directory
  ansible.builtin.set_fact:
    _docker_project_dir: "{{ dapp_common_directory }}/{{ role_name }}"

- name: Create project directory
  ansible.builtin.file:
    path: "{{ _docker_project_dir }}"
    state: directory

- name: Copy docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ _docker_project_dir }}/docker-compose.yml"
    mode: 0640
  no_log: true
  notify: Create and start containers

- name: Copy datasources.yml
  ansible.builtin.copy:
    content: "{{ dapp_grafana_datasources_yml }}"
    dest: "{{ _docker_project_dir }}/datasources.yml"
    mode: 0644
  notify: Restart containers

- name: Copy providers.yml
  ansible.builtin.copy:
    content: "{{ dapp_grafana_providers_yml }}"
    dest: "{{ _docker_project_dir }}/providers.yml"
    mode: 0644
  notify: Restart containers

- name: Copy ldap.toml
  ansible.builtin.copy:
    content: "{{ dapp_grafana_ldap_toml }}"
    dest: "{{ _docker_project_dir }}/ldap.toml"
    mode: 0640
  when: dapp_grafana_ldap_toml is defined
  no_log: true
  notify: Restart containers

- name: Copy dashboards
  ansible.builtin.copy:
    src: dashboards/
    dest: "{{ _docker_project_dir }}/dashboards/ansible"
  notify: Restart containers

- name: Copy grafana.env
  ansible.builtin.copy:
    content: "{{ dapp_grafana_env }}"
    dest: "{{ _docker_project_dir }}/grafana.env"
    mode: 0640
  no_log: true
  notify: Restart containers

- name: Start containers
  ansible.builtin.shell: |
    docker compose --project-directory "{{ _docker_project_dir }}" up -d
  changed_when: false

- name: Flush handlers
  meta: flush_handlers
