---
volumes:
  alertmanager:

networks:
  default:
  traefik_proxy:
    external: true

services:

  alertmanager:
    image: "{{ dapp_alertmanager_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "alertmanager"
    networks:
      - default
      - traefik_proxy
{% if dapp_alertmanager_docker_mem_limit is defined %}
    mem_limit: {{ dapp_alertmanager_docker_mem_limit }}
{% endif %}
    volumes:
      {{ dapp_alertmanager_volumes|to_nice_yaml|indent(6) }}
    environment:
      {{ dapp_alertmanager_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_alertmanager_docker_healthcheck|indent(6) }}
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.alertmanager.entrypoints: "http, https"
      traefik.http.routers.alertmanager.rule: "Host(`{{ dapp_alertmanager_traefik_address }}`)"
      traefik.http.services.alertmanager.loadbalancer.server.port: "9093"
{% if dapp_alertmanager_basicauth is defined %}
      # password hash: escape $ with a second $
      traefik.http.middlewares.alertmanagerauth.basicauth.users: "{{ dapp_alertmanager_basicauth | regex_replace('\$','$$') }}"
      traefik.http.routers.alertmanager.middlewares: "alertmanagerauth"
{% endif %}
{% if dapp_common_traefik_tls %}
      traefik.http.routers.alertmanager.tls: "true"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
      traefik.http.routers.alertmanager.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
      traefik.http.routers.alertmanager.tls.domains[0].main: "{{ dapp_alertmanager_traefik_address }}"
{% endif %}
