---
volumes:
  opensearch:

networks:
  traefik_proxy:
    external: true

services:

  app:
    image: "{{ dapp_opensearch_docker_image }}"
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: "opensearch"
    networks:
      - traefik_proxy
{% if dapp_opensearch_ports is defined %}
    ports: {{ dapp_opensearch_ports }}
{% endif %}
{% if dapp_opensearch_docker_mem_limit is defined %}
    mem_limit: {{ dapp_opensearch_docker_mem_limit }}
{% endif %}
    environment:
      {{ dapp_opensearch_docker_environment|indent(6) }}
    healthcheck:
      {{ dapp_opensearch_docker_healthcheck|indent(6) }}
{% if dapp_opensearch_ulimits is defined %}
    ulimits:
      {{ dapp_opensearch_ulimits|to_nice_yaml|indent(6) }}
{% endif %}
    volumes:
      {{ dapp_opensearch_volumes|to_nice_yaml|indent(6) }}
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_proxy"
      traefik.http.routers.opensearch.rule: "Host(`{{ dapp_opensearch_traefik_address }}`)"
      traefik.http.services.opensearch.loadbalancer.server.port: "9200"
{% if dapp_common_traefik_tls %}
      traefik.http.routers.opensearch.tls: "true"
{% endif %}
{% if dapp_common_traefik_tls and dapp_common_traefik_certresolver != "none" %}
      traefik.http.routers.opensearch.tls.certresolver: "{{ dapp_common_traefik_certresolver }}"
      traefik.http.routers.opensearch.tls.domains[0].main: "{{ dapp_opensearch_traefik_address }}"
{% endif %}
